FROM node:12

# actual dir doesn't matter - linux file system
# we will copy it into a directory called app
COPY . /opt/app 

# sets working directiry for any subsequent commands
WORKDIR /opt/app

RUN npm install
CMD npm run watch